name: NodeJS with Webpack

on:
  push:
    branches: [ "ter-v2" ]
  pull_request:
    branches: [ "ter-v2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Build dist
        run: |
          npm run build-prod

      - name: Build documentation
        run: npm run build-docs
